# Generated by Django 4.1.4 on 2022-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='TestsWeb/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
